# Generated by Django 3.2.9 on 2021-12-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swcharacter',
            name='rows_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
